openapi: 3.1.0
info:
  version: 1.0.0
  title: Binary Shift app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Binary Shift app
tags:
  - name: Binary Shift
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:8080
  - url: https://example.com/api/v1
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/logout.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
