openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |-
    This is a documentation of Water Tracker App

    *Functional capabilities:**

    User registration and authorization

    Password recovery by mail

    Editing general user information

    Editing a user's profile avatar

    Adding, editing and deleting records of the amount of water consumed

    Receiving an array of aggregated information on user records during the month for each day

    Display of all records for a single day

    Display of the daily rate of water selected by the user

    Editing of the daily rate of water selected by the user

    **The technology stack used in the project:**

    Node.js - JavaScript runtime on the server

    Express.js - A framework for developing web applications on Node.js

    MongoDB - NoSQL database

    Mongoose - A library for working with MongoDB in Node.js
tags:
  - name: Users
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Water
    description: Operations with records of water consumption.
  - name: WaterRate
    description: Operations with the daily rate of water selected by the user.
  - name: Month
    description: Returning summary information about days for a month.
  - name: Today
    description: Returning all records of water consumption for the day.
servers:
  - url: http://localhost:8080
  - url: https://binary-shift-backend.onrender.com
paths:
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/logout.yaml
  /user/{id}:
    patch:
      $ref: ../swagger/paths/user/{id}/patch.yaml
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/patchAvatar.yaml
  /user/request-reset-email:
    post:
      $ref: ../swagger/paths/user/requestResetEmail.yaml
  /user/reset-password:
    post:
      $ref: ../swagger/paths/user/resetPwd.yaml
  /month:
    get:
      $ref: ../swagger/paths/month/get.yaml
  /water-rate:
    get:
      $ref: ../swagger/paths/waterRate/get.yaml
    put:
      $ref: ../swagger/paths/waterRate/put.yaml
  /today:
    get:
      $ref: ../swagger/paths/today/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
